
// export const GET_STAFF = "GET_STAFF";
// export const ADD_STAFF = "ADD_STAFF";
// export const DELETE_STAFF = "DELETE_STAFF";
// export const STAFF_LOADING = "STAFF_LOADING";
export const FETCH_STAFF_REQUEST = "FETCH_STAFF_REQUEST";
export const FETCH_STAFF_SUCCESS = "FETCH_STAFF_SUCCESS";
export const FETCH_STAFF_FAIL = "FETCH_STAFF_FAIL";
export const FETCH_DETAIL_REQUEST = "FETCH_DETAIL_REQUEST";
export const FETCH_DETAIL_SUCCESS = "FETCH_DETAIL_SUCCESS";
export const FETCH_DETAIL_FAIL = "FETCH_DETAIL_FAIL";



